luk_repchatyy = "https://online.globus.ru/products/luk-repchatyy-1-kg/"
svekla = "https://online.globus.ru/products/svekla-1-kg/"
kartofel = "https://online.globus.ru/products/kartofel-fasovannyy-belyy-1-upakovka-5-09-5-22-kg/"
morkov = "https://online.globus.ru/products/morkov-molodaya-fermerskaya-1-kg/"
kapusta = "https://online.globus.ru/products/kapusta-belokochannaya-1-1-3-7-kg/"
chesnok_svejiy = "https://online.globus.ru/products/chesnok-1-kg/"
petrushka_zelenaya = "https://online.globus.ru/products/petrushka-bogoslovo-argo-100-g/"
pasta_tomatnaya = "https://online.globus.ru/products/pasta-tomatnaya-pomidorka-s-pryanymi-travami-i-chesnokom-270-g/"
uksus_yablochnyy = "https://online.globus.ru/products/uksus-yablochnyy-setra-4-250-ml/"
lavrovyy_list = "https://online.globus.ru/products/lavrovyy-list-globus-10-g/"
sahar = "https://online.globus.ru/products/sakhar-rafinad-russkiy-sakhar-500-g/"
sol = "https://online.globus.ru/products/chernaya-sol-gimalayskaya-ufeelgood-molotaya-200-g/"
perets_chernyy = "https://online.globus.ru/products/perets-chernyy-globus-goroshkom-40-g/"
smetana_15 = "https://online.globus.ru/products/smetana-prostokvashino-15-300-g/"

list_products = [luk_repchatyy,svekla,kartofel,morkov,kapusta,chesnok_svejiy,petrushka_zelenaya,pasta_tomatnaya,uksus_yablochnyy,lavrovyy_list,sahar,sol,perets_chernyy,smetana_15]
